export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER  = 'SET_CURRENT_USER';


export const FETCH_USER_EVENTS = 'FETCH_USER_EVENTS';
export const DELETE_USER_EVENT = 'DELETE_USER_EVENT';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
